-- Platform: DataLemur

-- Problem: Highest-Grossing

-- Link: https://datalemur.com/questions/sql-highest-grossing

-- Concept: CTE, DENSE_RANK().

-- Query
WITH highest_grossing_products AS (

    SELECT
        category,
        product,
        SUM(spend) AS total_spend,

        DENSE_RANK() OVER (
            PARTITION BY category
            ORDER BY SUM(spend) DESC
        ) AS ranking

    FROM product_spend

    WHERE EXTRACT(YEAR FROM transaction_date) = 2022

    GROUP BY category, product
)

SELECT
    category,
    product,
    total_spend
FROM highest_grossing_products
WHERE ranking <= 2;


/*
Explanation: Since the analysis required ranking products inside each category, I used a Common Table Expression (CTE) to make the query cleaner and easier to manage.
I filtered the dataset to include only transactions from 2022 because the ranking should be based only on that year’s sales data.
Then, I grouped the data by category and product to calculate total spending for every product within its category.
I used SUM(spend) to measure total revenue generated by each product.
After calculating total sales, I needed to rank products within each category, so I applied the DENSE_RANK() window function.
I partitioned the ranking by category so each category would have its own separate ranking sequence.
Then, I ordered the ranking by SUM(spend) DESC to ensure the highest-selling products received the top ranks.
I used DENSE_RANK() instead of ROW_NUMBER() because products with the same sales value should receive the same rank without skipping numbers.
Once the ranking was created inside the CTE, I filtered the final result to keep only products with ranks less than or equal to 2.
The final output returns the top 2 highest-grossing products from each category based on total sales in 2022.
*/