-- Platform: DataLemur

-- Problem: Total-Drugs-Sales

-- Link: https://datalemur.com/questions/total-drugs-sales

-- Concept: GROUP BY, ORDER BY, CONCAT, ROUND, SUM.

-- Query
SELECT 
  manufacturer,
  CONCAT('$', ROUND(SUM(total_sales)/1000000, 0), ' million') AS sale
FROM pharmacy_sales
GROUP BY manufacturer
ORDER BY SUM(total_sales) DESC;


/*
Explanation: Started by calculating and displaying total sales generated by each manufacturer in millions.
Selected the pharmacy_sales table because it contains manufacturer details and sales revenue data.
Chose the manufacturer column to analyze sales performance company-wise.
Used SUM(total_sales) to calculate the total sales generated by each manufacturer.
Divided the total sales by 1,000,000 to convert the value into millions for easier business reporting.
Applied ROUND(..., 0) to round the sales amount to the nearest whole number.
Used the CONCAT() function to format the output as currency text in the form of '$X million'.
Renamed the formatted sales value as sale for better readability.
Grouped the records by manufacturer to calculate total sales separately for each company.
Used ORDER BY SUM(total_sales) DESC to rank manufacturers from highest sales to lowest sales.
Solved the problem by generating a manufacturer-wise sales summary in a business-friendly format.
*/